
# Set the current design
current_design rv32i_core

create_clock -name "clk_main" -period 20.0 -waveform {0.0 10.0} [get_ports clk]
set_load -pin_load 100.0 [get_ports instr_mem_req_o]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[31]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[30]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[29]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[28]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[27]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[26]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[25]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[24]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[23]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[22]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[21]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[20]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[19]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[18]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[17]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[16]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[15]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[14]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[13]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[12]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[11]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[10]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[9]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[8]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[7]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[6]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[5]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[4]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[3]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[2]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[1]}]
set_load -pin_load 100.0 [get_ports {instr_mem_addr_o[0]}]
set_load -pin_load 100.0 [get_ports data_mem_readreq_o]
set_load -pin_load 100.0 [get_ports data_mem_writereq_o]
set_load -pin_load 100.0 [get_ports {data_mem_addr[31]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[30]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[29]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[28]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[27]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[26]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[25]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[24]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[23]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[22]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[21]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[20]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[19]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[18]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[17]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[16]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[15]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[14]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[13]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[12]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[11]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[10]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[9]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[8]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[7]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[6]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[5]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[4]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[3]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[2]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[1]}]
set_load -pin_load 100.0 [get_ports {data_mem_addr[0]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[31]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[30]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[29]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[28]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[27]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[26]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[25]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[24]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[23]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[22]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[21]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[20]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[19]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[18]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[17]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[16]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[15]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[14]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[13]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[12]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[11]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[10]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[9]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[8]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[7]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[6]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[5]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[4]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[3]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[2]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[1]}]
set_load -pin_load 100.0 [get_ports {data_mem_write_data[0]}]
set_load -pin_load 100.0 [get_ports {data_mem_funct3[2]}]
set_load -pin_load 100.0 [get_ports {data_mem_funct3[1]}]
set_load -pin_load 100.0 [get_ports {data_mem_funct3[0]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[31]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[30]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[29]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[28]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[27]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[26]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[25]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[24]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[23]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[22]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[21]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[20]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[19]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[18]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[17]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[16]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[15]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[14]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[13]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[12]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[11]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[10]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[9]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[8]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[7]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[6]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[5]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[4]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[3]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[2]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[1]}]
set_load -pin_load 100.0 [get_ports {data_mem_data_o[0]}]
set_false_path -from [get_ports reset_n]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[31]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[30]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[29]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[28]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[27]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[26]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[25]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[24]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[23]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[22]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[21]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[20]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[19]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[18]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[17]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[16]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[15]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[14]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[13]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[12]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[11]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[10]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[9]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[8]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[7]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[6]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[5]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[4]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[3]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[2]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[1]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_data_i[0]}]
set_input_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports reset_n]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports instr_mem_req_o]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[31]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[30]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[29]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[28]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[27]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[26]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[25]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[24]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[23]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[22]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[21]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[20]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[19]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[18]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[17]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[16]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[15]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[14]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[13]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[12]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[11]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[10]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[9]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[8]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[7]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[6]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[5]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[4]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[3]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[2]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[1]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {instr_mem_addr_o[0]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports data_mem_readreq_o]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports data_mem_writereq_o]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[31]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[30]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[29]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[28]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[27]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[26]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[25]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[24]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[23]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[22]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[21]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[20]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[19]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[18]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[17]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[16]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[15]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[14]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[13]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[12]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[11]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[10]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[9]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[8]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[7]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[6]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[5]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[4]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[3]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[2]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[1]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_addr[0]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[31]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[30]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[29]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[28]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[27]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[26]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[25]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[24]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[23]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[22]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[21]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[20]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[19]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[18]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[17]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[16]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[15]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[14]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[13]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[12]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[11]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[10]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[9]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[8]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[7]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[6]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[5]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[4]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[3]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[2]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[1]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_write_data[0]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_funct3[2]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_funct3[1]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_funct3[0]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[31]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[30]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[29]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[28]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[27]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[26]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[25]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[24]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[23]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[22]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[21]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[20]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[19]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[18]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[17]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[16]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[15]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[14]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[13]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[12]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[11]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[10]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[9]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[8]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[7]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[6]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[5]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[4]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[3]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[2]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[1]}]
set_output_delay -clock [get_clocks clk_main] -add_delay 1.0 [get_ports {data_mem_data_o[0]}]
set_max_fanout 15.000 [current_design]
set_max_transition 2.0 [current_design]
set_drive 0.004 [get_ports clk]
set_drive 0.004 [get_ports reset_n]
set_drive 0.004 [get_ports {instr_mem_data_i[31]}]
set_drive 0.004 [get_ports {instr_mem_data_i[30]}]
set_drive 0.004 [get_ports {instr_mem_data_i[29]}]
set_drive 0.004 [get_ports {instr_mem_data_i[28]}]
set_drive 0.004 [get_ports {instr_mem_data_i[27]}]
set_drive 0.004 [get_ports {instr_mem_data_i[26]}]
set_drive 0.004 [get_ports {instr_mem_data_i[25]}]
set_drive 0.004 [get_ports {instr_mem_data_i[24]}]
set_drive 0.004 [get_ports {instr_mem_data_i[23]}]
set_drive 0.004 [get_ports {instr_mem_data_i[22]}]
set_drive 0.004 [get_ports {instr_mem_data_i[21]}]
set_drive 0.004 [get_ports {instr_mem_data_i[20]}]
set_drive 0.004 [get_ports {instr_mem_data_i[19]}]
set_drive 0.004 [get_ports {instr_mem_data_i[18]}]
set_drive 0.004 [get_ports {instr_mem_data_i[17]}]
set_drive 0.004 [get_ports {instr_mem_data_i[16]}]
set_drive 0.004 [get_ports {instr_mem_data_i[15]}]
set_drive 0.004 [get_ports {instr_mem_data_i[14]}]
set_drive 0.004 [get_ports {instr_mem_data_i[13]}]
set_drive 0.004 [get_ports {instr_mem_data_i[12]}]
set_drive 0.004 [get_ports {instr_mem_data_i[11]}]
set_drive 0.004 [get_ports {instr_mem_data_i[10]}]
set_drive 0.004 [get_ports {instr_mem_data_i[9]}]
set_drive 0.004 [get_ports {instr_mem_data_i[8]}]
set_drive 0.004 [get_ports {instr_mem_data_i[7]}]
set_drive 0.004 [get_ports {instr_mem_data_i[6]}]
set_drive 0.004 [get_ports {instr_mem_data_i[5]}]
set_drive 0.004 [get_ports {instr_mem_data_i[4]}]
set_drive 0.004 [get_ports {instr_mem_data_i[3]}]
set_drive 0.004 [get_ports {instr_mem_data_i[2]}]
set_drive 0.004 [get_ports {instr_mem_data_i[1]}]
set_drive 0.004 [get_ports {instr_mem_data_i[0]}]
set_clock_uncertainty -setup 1.0 [get_clocks clk_main]
set_clock_uncertainty -hold 0.2 [get_clocks clk_main]
